library(tidyverse)
library(readxl)
library(rebus)
library(tidytext)

df_original <- readRDS("Intermediate/df_clean.rds")

df_semantic <- readRDS("Intermediate/df_semantic_similarity.rds")

df_sequential <- readRDS("Intermediate/df_sequential_search.rds")

df_single <- readRDS("Intermediate/df_single_word_skills.rds")

esco_single <- readRDS("Intermediate/esco_original_1_single_word.rds")

esco_original_1 <- readRDS("Intermediate/esco_original_1.rds")

switch_table <- readRDS("Intermediate/switch_table.rds")


# SPLITTING ROWS FOR EACH SKILL -------------------------------------------

# skills extractions datasets are merged together

df <- bind_rows(df_semantic %>% mutate(doc_id_esco = as.character(doc_id_esco)),
                df_sequential %>% mutate(doc_id_esco = as.character(doc_id_esco)), 
                df_single %>% mutate(doc_id_esco = as.character(doc_id_esco)) )

# the skills extracted from each sentence are been splitted in duplicated rows so that each observation
# of the dataset is a single skill extracted
# in addiction duplicated skills are been removed becuase in the same sentence must be only one skill
# of a kind

df <- separate_rows(df, skills_list, doc_id_esco, sep = " \\; ") %>%  #be carefull that empty rows will be deleted
  distinct(overall_id, skills_list, .keep_all = T) %>% 
  filter(str_detect(skills_list, WRD) & !is.na(skills_list))


# SKILLS PATTERN CORRECTION -----------------------------------------------


#  some correction to skills label here

pattern_fix <- esco_single %>% 
  select(preferredLabel) %>% 
  distinct(preferredLabel) %>% 
  mutate(skill = str_to_lower(preferredLabel))

# skills label correction are applied to the skills dataset

df  <- df %>% 
  left_join(pattern_fix, by = c("skills_list" = "skill")) %>% 
  mutate(skills_list = if_else(!is.na(preferredLabel), preferredLabel, skills_list)) %>% 
  select(-preferredLabel) %>% 
  mutate(skills_list = if_else(skills_list == "c", "C++", skills_list)) %>% 
  mutate(skills_list = if_else(skills_list == "aspp", "ASP+", skills_list)) %>% 
  mutate(skills_list = if_else(skills_list == "asp", "ASP+", skills_list))


# ALTERNATIVE LABELS REPLACE WITH PREFERRED --------------------------------------------

#use the switch table to substitute the alternative labels 

df <- df %>% 
  left_join(switch_table, by = c("skills_list" = "altLabels")) %>% 
  mutate(skills_list = if_else(!is.na(preferredLabel), preferredLabel, skills_list)) %>% 
  mutate(doc_id_esco = if_else(!is.na(doc_id_esco_x), doc_id_esco_x, doc_id_esco)) %>% 
  select(-doc_id_esco_x, -preferredLabel) %>% 
  distinct(overall_id, skills_list, .keep_all = T) %>% #removing duplicates generated by the alternative label substitution
  filter(str_detect(skills_list, WRD) & !is.na(skills_list))


# JOIN SKILLS EXTRACTION DATASET WITH THE ORIGINAL SENTENCES DATAS --------

# join the skills to the original sentences dataset and add esco ontology metadata to the skills

final_dataset <- df_original %>% 
  left_join(df %>% select(skills_list, overall_id, doc_id_esco), by = "overall_id") %>% 
  left_join(esco_original_1 
            %>% mutate(doc_id_esco = as.character(doc_id_esco)) 
            %>% select(-preferredLabel), # nb esco orignal 1 have only the preferred label column as we want
            by = c("doc_id_esco" = "doc_id_esco")) 

# there is a little problem that consist in the presence of some alt label without a preferred label
# father this because in the zero script the skill number of word filtering is done with prefferred
# and alt label togheter and if the preferred label has more than 6 words and their sons alt label
# have less or equal than 6 words the alt labels remain uncoupled from their preferred labels father

tresh <- final_dataset %>% #check that the problem is under control
  filter((is.na(Level.3.preferred.term) & !is.na(skills_list)))

# now is very important to note that due to the left join the original overall_id will be duplicated when
# a single sentences contains more than one skills so that overall id is not anymore univoque and we have
# to create a new unique id for the new dataset that has the skill as observations

final_dataset <- final_dataset %>% 
  filter(!(is.na(Level.3.preferred.term) & !is.na(skills_list))) %>%  # filter the uncoupled alt labels
  arrange(overall_id) %>% 
  mutate(final_dataset_id = row_number()) %>% 
  select(-n, -lemma_txt, -clean_txt)

# finally we have the complete dataset with the skills metadata


# OUTPUT GENERATION -------------------------------------------------------

write_rds(final_dataset, "Intermediate/df_complete_skills.rds")

